---
title: "Classic Momentum"
subtitle: "How to smack things together"
author: "Kevin Rozmiarek"
date: "Last knitted `r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_float: true
    toc_depth: 3
    code_folding: show
editor_options:
  chunk_output_type: inline
---

# Learning Goals

1. Understand that momentum is conserved in collisions.

2. Understand the difference between **elastic** and **inelastic** collisions

3. Be able to balance and compute the momentum of objects in **elastic** collisions.

# Background

Momentum is a quality of everything! It is the quantity of motion of a moving body, measured as a product of its mass and velocity. Momentum by itself isn't all that interesting, only when it comes to collisions! Let's talk about two different kinds of collisions first.

**Elastic collision:** An elastic collision is an encounter between two bodies in which the total momentum and kinetic energy of the two bodies remains the same. In an ideal, perfectly elastic collision, there is no net conversion of kinetic energy into other forms such as heat, noise, or potential energy.

**Inelastic Collision:** An inelastic collision, in contrast to an elastic collision, is a collision in which momentum and kinetic energy is not conserved due to the action of internal forces within the objects, like friction.

Because we don't want to have to worry about pesky things like heat, noise, and potential energy, we are going to work with elastic collisons. Now consider the momentum $\rho$ of an object of mass $m$ and velocity $v$. Momentum is then.
$$
\rho = mv
$$
Because momentum is **conserved** in elastic collisions, momentum of a system is the summation of is parts. Take for example two cars moving in the same direction with masses $m_{1}$ and $m_{2}$ and velocities $v_{1}$ and $v_{2}$ respectively. The total mass of the system is then:

$$
\rho_{total}=m_{1}v_{1}+m_{2}v_{2}=\rho_{1}+\rho_{2}
$$
Because of this conservation, we can explore the concept of many differing colliding objects seen below in our example.

# Example

Two cars are barreling towards another car in a future ellastic collision. Their masses and velocities are listed below. A negative sign in this case is going to indicate to us that the car is travelling in the opposite direction as the other two. Lets use R to calculate the total mass of the system!

```{r, message=FALSE}
library(tidyverse)

# session info
masses <- c(300, 400, 600)
velocties <- c(20, 10, -15)

total_momentum <- sum(masses*velocties)
print(total_momentum)

```

And there you go! The total momuntum of the system is 1000! More specifically it is $kg⋅m/s$. This implies that though to one car is hitting the other two. The three will still continue onwards in the direction of the original two.... though perhaps slower than before.

# Questions

1. You just got your BB gun for Christmas but all is for naught because an astroid is bearing down on Earth! The astroid is $1  \times 10^{15} kg$ and moving at $2 \times 10^{4} m/s$. Fortunately you have quite a few BBs which weigh $0.0002 kg$ and you can fire them at $60 m/s$. How many BBs will it take to stop the astroid and save Earth assuming this is an elastic collision? Show the expression you used to calculate this.

2. Rank these cars by their momentum.
  * Car 1: $800 kg$ going $1 m/s$
  * Car 2: $1000 kg$ going $2 m/s$
  * Car 3: $90 kg$ going $8 m/s$

3. I am going to claim that momentum is always conserved, even in inelastic collisions. If that is true and you watched something heat up (say a [chicken](https://www.wired.com/story/how-many-times-do-you-have-to-slap-a-chicken-to-cook-it/)) by something hitting it, speculate where the momentum goes if the chicken doesn't move as fast as you'd expect after the collison.